// Code generated by oapi-codegen (placeholder). DO NOT EDIT.
package openapi

// Минимальные типы под openapi.yml, чтобы компилировалось до генерации.

type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

type TeamMember struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
}

type Team struct {
	TeamName string       `json:"team_name"`
	Members  []TeamMember `json:"members"`
}

type PullRequestShort struct {
	ID        string   `json:"id"`
	Title     string   `json:"title"`
	AuthorID  string   `json:"author_id"`
	Status    string   `json:"status"`
	Reviewers []string `json:"reviewers"`
}

type PullRequest struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	AuthorID  string       `json:"author_id"`
	Status    string       `json:"status"`
	Reviewers []TeamMember `json:"reviewers"`
}
